### ISSUE TITLE
Update readme 

### ISSUE THREAD

**Issue by ashish979** [activitree/meteor-push#1]
Hi @paulincai 

If you got this working with Android 8+, Please update the readme or send a sample usage repo so that we can use it too.

Also, we are looking forward to work on meteor. So, we will be happy to contribute too.

Thanks

**Comment by tiagohintz** [comment]
Hi @paulincai 

Is it possible to share an example so we can help you assemble the documentation?

Thanks

**Comment by paulincai** [comment]
@ashish979 @tiagohintz Will start working on this today.
