### ISSUE TITLE
Current version of node-apn does not support iOS13 apns-push-type

### ISSUE THREAD

**Issue by ninefivetwo** [activitree/meteor-push#11]
I still believe push notifications won't work for iOS13 due to the missing apns-push-type https://github.com/node-apn/node-apn/pull/656. The thing is node-apn still needs to publish the new version on npm.

The alternative is to switch to a fork of node-apn https://github.com/parse-community/node-apn which is currently maintained.

**Comment by paulincai** [comment]
Hi @ninefivetwo, I have another repo for testing IOS tokens with APN. I will run some tests and see what goes through.. https://github.com/activitree/NODE-APN-Notifications-Tester

**Comment by paulincai** [comment]
Moving over to Firebase FCM. Firebase-Admin is a little ... big and super scoped for what we need here. I'd use Firebase Admin if we saved token with Firebase but we only use a small module there, for messaging. This means on single library for IOS, Android, and Web/PWA

**Comment by ninefivetwo** [comment]
Yes this is true.
But I don't think we need to move iOS push notifications over to FCM to address this issue.
The easier option is switching out the apn-node dependency to @parse/node-apn.

**Comment by paulincai** [comment]
when you say "we" who exactly are you referring to? Do you mean your team?
I am not sure relying on a community maintained package is the way forward when I can hook into "official" tech. Moreover, I could you one single library and method to send for all three: IOS, Android and Web. The last 2 are already configured now.
If I drop APN, configuration also become very simple with all configuration outside Meteor done once in one single place.
Do you have a particular need, preference or standard for IOS over APN?

**Comment by ninefivetwo** [comment]
> when you say "we" who exactly are you referring to? Do you mean your team?

I was referring to this package.

> Do you have a particular need, preference or standard for IOS over APN?

No I don't. I was just thinking for this particular issue, the easiest and quickest way to get it fixed is to change the package that is being used.
