### ISSUE TITLE
Massive push notifications

### ISSUE THREAD

**Issue by AleF1** [activitree/meteor-push#19]
Is there a way to send a push notification to all users the same way you do it via firebase web? I can't seem to get it to work properly. It sends all of the notifications but only around 100 users receive them. Maybe they have to be grouped in batches? No idea...

**Comment by paulincai** [comment]
Hi @AleF1,
I do not know how you send it via firebase web.
1. Are you sending one notification to a userIds list?
2. Or are you sending multiple notifications to a userId (map through your users and call a Push method for each user)?
3. Do you have debugging turned on and can confirm that a particular user (token) is being sent a notification successfully but the notification is not received?

I do not see any reasons to have a limitation. It is more like ... your server crushes or everything goes from start to end.
