### ISSUE TITLE
Track notifications analytics

### ISSUE THREAD

**Issue by AleF1** [activitree/meteor-push#20]
Is there any way to track notifications in the firebase console?

**Comment by paulincai** [comment]
Hi @AleF1,
you have some basic API reporting here (success/fail): https://console.cloud.google.com/apis/api/fcm.googleapis.com/overview?project=your_project.

For more detailed analytics, I guess you could use this: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidfcmoptions
which as I can see in the project is only half implemented (both IOS and Android). It exists in the final notification constructor but it is missing from the notification data validation which means...if you need it, it should be pretty easy to get it running with a very small update.
Which one cover your present needs: Google Console or the Analytics field as described in the second link?

**Comment by AleF1** [comment]
Thanks for the quick answer @paulincai. The second link is what I'm looking for but I do have an analytics label on push startup. It may not be doing anything cause there's no validation... No clue tho.

**Comment by paulincai** [comment]
Ok, that is should be passed to the final notification. Look at ```defaults.analyticsLabel```
```javascript
fcm_options: {
        analytics_label: mongoNote.analyticsLabel || defaults.analyticsLabel,
        image: mongoNote.imageUrl || defaults.imageUrl
      }
```

So, if you have a label set in your server side startup file and if you enable debugging, you should see that value in your server console when you send a notification.
