### ISSUE TITLE
Question: Does this work in Meteor 1.6+ 

### ISSUE THREAD

**Issue by lokiribeiro** [activitree/meteor-push#22]
Hi,

This is more of a question. Does this work for Meteor 1.6? I cant seem to make apn push notification to work from raix due to the certificates; I keep getting error code 8 when sending notifications even tho Im using the right certificates for production / development and i wanted to use p8 files instead.

**Comment by paulincai** [comment]
@lokiribeiro you would need at least Meteor 1.8.1. This is the time when the Cordova components in Meteor were updated.
https://github.com/meteor/meteor/blob/devel/History.md#breaking-changes-3

Cordova compatibility chart: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#installation-requirements

This Push project uses phonegap-plugin-push@2.3.0.

There is a lot of new tech there and couldn't keep glued to such old versions. I think it is needless to say that best would be if you could move your project to latest Meteor and benefit from all those goodies, especially Node12, Mongo 4.2 with 3.5 driver and most important ... easy upgradability to Meteor 1.10.

A far more updated Push package than Raix is the V1 of this package which works with Meteor 1.6.

**Comment by lokiribeiro** [comment]
Hi @paulincai , for v1 of this project does it use p8 certificate for apn?

**Comment by paulincai** [comment]
@lokiribeiro  Yes: https://github.com/activitree/meteor-push/tree/45d97977c37d70d561fcdc4cd78e3af3bc910e88

You might be lucky and possibly avail of a path to move Meteor 1.6 straight up to the latest Cordova version. Check this discussion and perhaps Filipe can give you the "how to" https://forums.meteor.com/t/meteor-1-6-how-do-i-get-upgrade-to-latest-cordova/40486/9.
In this case you should be able to use V2 of this Push package.

**Comment by lokiribeiro** [comment]
Alright, so im migrating from raix:push. Does it use the same configure options and syntax for sending notifications?

**Comment by paulincai** [comment]
@lokiribeiro you may find all these answers in the repo.
