### ISSUE TITLE
EventState is not defined

### ISSUE THREAD

**Issue by jamauro** [activitree/meteor-push#28]
I'm running Meteor 1.11. Here's the error message:

```
ReferenceError: EventState is not defined at module (packages/activitree:push/lib/server/pushToDB.js:6:14)
```

When I added `activitree:push` for some reason `raix:eventstate@0.0.6` was added even though it looks like `@0.0.5` is listed as a dependency. Not sure if that matters.

Any ideas?

**Comment by paulincai** [comment]
Hi, the dependency was supposed to install with no issue. I have also noticed more than a month back that for some reasons this is no longer happening. The owner of the ```eventstate``` package (Raix) has deprecated all his packages. I am testing now a package that includes that in the build and not as dependency. Would you like to help test this?

**Comment by jamauro** [comment]
I'll be happy to help test but that link is a 404 🙂

**Comment by paulincai** [comment]
@jamauro in the main repo, you can take the folder lib and the file package.js and use it as a local package in your meteor project.
In case you haven't used a local package before, in the root of your app (same folder where you have your main package.json or settings.json) create a folder named ```packages```. Within this folder create another folder called for instance ```meteor-push``` and copy the lib folder mentioned above and the package.js file. Remove activitree:push, delete all versions of activitree:push from your local stations (on a Mac, in your user folder .meteor/packages/....) then ```meteor add activitree:push```. The installation will come from the local folder.
I tested the Web push in production and all looks ok but I don't have a Cordova project at this time so I would really appreciate your feedback.

**Comment by jamauro** [comment]
Initial testing looks good on iOS Cordova. Thanks for updating.
