### ISSUE TITLE
iOS error after clicking on notification

### ISSUE THREAD

**Issue by jamauro** [activitree/meteor-push#29]
<img width="1001" alt="Screen Shot 2020-10-04 at 2 48 38 PM" src="https://user-images.githubusercontent.com/1749828/95025616-c0feb380-0650-11eb-9362-ad69ab14e5d4.png">

Seeing this after clicking on the notification. Any ideas?

**Comment by paulincai** [comment]
If you activate the debugger, what do you get in this area?! https://github.com/activitree/meteor-push/blob/d9f15355ca8a2cca4c67e1c37f9057e5d00628a5/lib/client/cordova.js#L86

You can add more console.logs to try to determine where the error occurs. ```this.push``` is a global variable coming from the cordova push plugin. The issue may be in activitree:push (if possible introduced with renouncing the old event emitter and  adding the new emitter library in the last update) or in the plugin itself.

**Comment by paulincai** [comment]
Closed due to lack of interaction
