### ISSUE TITLE
Data message not working

### ISSUE THREAD

**Issue by dsmalicsi** [activitree/meteor-push#3]
Hi, I have encountered this issue when trying to send a `data` message.
It's throwing a validation error, but based from your example method code, `data` should be accepted right? I hope it gets fixed, thanks!

```
I20190519-17:20:48.720(8)?   message: 'Match error: Unknown key in field data',
I20190519-17:20:48.720(8)?   path: 'data',
```

**Comment by paulincai** [comment]
Hi @dsmalicsi , "data" is not yet developed. May I please have a sample of what you would like to send?

**Comment by dsmalicsi** [comment]
Hi @paulincai thanks for letting me know. I'd like to use it for sending notifications with pictures. See below example
```
"data": {
    "title": "Test Notification",
    "message": "Send message",
    "style": "picture",
    "image": "http://www.example.com/image.jpg",
    "picture": "http://www.example.com/image.jpg",
    "summaryText": "Summary Text"
  }
```

**Comment by paulincai** [comment]
Fixed in V2. Also answered here: https://github.com/activitree/meteor-push/issues/5#issuecomment-547498376
