### ISSUE TITLE
Can't add package

### ISSUE THREAD

**Issue by rebeccaplowman** [activitree/meteor-push#33]
I removed the activitree:push package in order to try solving an issue with running my meteor project. Now I can't add it to any project. This is the error I get:
![Screen Shot 2021-01-25 at 2 16 51 PM](https://user-images.githubusercontent.com/77806274/105767340-30f2bb80-5f18-11eb-82f0-4e60c99fd587.png)

**Comment by paulincai** [comment]
Hi, not related to this package. You may try: https://stackoverflow.com/questions/58735601/meteor-cant-read-entire-resource-file-while-building

**Comment by rebeccaplowman** [comment]
I've done further bug testing on this, and I still believe there is a problem with this package. My steps are as follows:

- I deleted my local folder, and cloned my project's repo. I ran 'meteor list', and received the list of packages as expected. I then checked out the branch I had been working on with activitree:push, and ran 'meteor list' again. As you can see in this screenshot below, I got 'Error: couldn't read entire resource'. I manually removed the activitree:push package from the Meteor packages file, and ran 'meteor list' again. I got the list of packages, as expected.

![Screen Shot 2021-01-26 at 10 16 12 AM](https://user-images.githubusercontent.com/77806274/105881079-5091ee80-5fc1-11eb-810e-c58a86c05d30.png)

- I opened a different project, that has never had activitree:push and has had no build or run errors. Trying to add activitree:push resulted in the same error, as you can see in the screenshot below.

![Screen Shot 2021-01-26 at 10 21 40 AM](https://user-images.githubusercontent.com/77806274/105881115-5b4c8380-5fc1-11eb-9c97-dfab7990ef39.png)

- I have also removed and added other Meteor packages to these projects, and received no errors.

**Comment by paulincai** [comment]
Did you try on a second machine as mentioned in the link I previously attached?
