### ISSUE TITLE
iOS 13 bad device token

### ISSUE THREAD

**Issue by jamauro** [activitree/meteor-push#7]
Looks like Apple changed something and now I'm seeing `Bad Device Token` in iOS 13 and this `device: {length = 32, bytes = 0x965b251c 6cb1926d e3cb366f dfb16ddd ... 5f857679 376eab7c }`

I found this article which has more details: https://nshipster.com/apns-device-tokens/

I'm not sure if this should be resolved in this package or `node-apn`. Thoughts?

**Comment by paulincai** [comment]
Hi @jamauro. I think this is related to https://github.com/phonegap/phonegap-plugin-push/issues/2819 . Within the Meteor package we only take what is being provided and save it to Mongo. In /lib/client/cordova.js line 70, PushNotification is coming from the Push Cordova plugin (https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md)

**Comment by jamauro** [comment]
Ok thanks for pointing me in the right direction!

**Comment by ninefivetwo** [comment]
> I think this is related to [phonegap/phonegap-plugin-push#2819](https://github.com/phonegap/phonegap-plugin-push/issues/2819)

It looks like a fix for it has been merged and published with version 2.3.0?

**Comment by jamauro** [comment]
Confirmed that phonegap-plugin-push@2.3.0 fixes this issue.
